background = 0xFFFBF1C7
base = 0xFFF2E5BC
text = 0xFF3C3836
alternate_base = 0xFFEBDBB2
bright_text = 0xFF3C3836
accent = 0xFF458588
link_text = 0xFF076678
accent_secondary = 0xFFB16286
font_family = "IBM Plex Mono"
font_family_monospace = "monospace"
font_size = 13
small_font_size = 10
rounding_large = 0
rounding_small = 0
